Tres novas ativididades adicionadas
GANESH-ICMC/ganesh-website pull request #4
Opened 2019-10-29 17:20 UTC by kakomarina

2019-10-30 00:06 UTC, Es7evam requested changes
Please fix the event dates

2019-10-30 00:06 UTC, Es7evam commented on pages/activities/atividade4.js
> +            <h3 className="news-date text-xs pb-2 xl:pb-4">05/12/1999</h3>
Please fix the dates :)

2019-10-30 00:06 UTC, Es7evam commented on pages/activities/atividade5.js
> +            <h3 className="news-date text-xs pb-2 xl:pb-4">05/12/1999</h3>
another date to be fixed

2019-10-30 00:06 UTC, Es7evam commented on pages/activities/atividade6.js
> +            <h3 className="news-date text-xs pb-2 xl:pb-4">05/12/1999</h3>
the last date fix

2020-04-05 14:16 UTC, Viana2021 commented on pages/activities/atividade5.js
> +            <h3 className="news-date text-xs pb-2 xl:pb-4">05/12/1999</h3>
Date fixed

2020-04-05 14:17 UTC, Viana2021 commented on pages/activities/atividade6.js
> +            <h3 className="news-date text-xs pb-2 xl:pb-4">05/12/1999</h3>
Date fixed

2020-04-05 14:21 UTC, merged